### PR TITLE
set sideEffects to None

### LINKED ISSUE #13: externalip-webhook prevents kubectl diff
Since the externalip-webhook does not specify any `sideEffects` its value defaults to `unknown` which prevents that
```
kuebctl diff ...
```
succeeds.
This error is shown
```
Error from server (BadRequest): admission webhook "validate-externalip.webhook.svc" does not support dry run
```

I think it is safe to just add `sideEffects: None` but I'm not 100% sure. Please let me know what you think.

### PR DESCRIPTION
**Pull request by TheKangaroo**
This ist the suggested PR/fix  mentioned in #13

### CODE REVIEW

**Comment by TheKangaroo** [comment]
I think I changed the commit message to comply with the guidelines, but the label won't be removed. Please let me know if there is still something wrong with my commit message 😇

**Comment by SaranBalaji90** [comment]
Thank you @TheKangaroo for the PullRequest. Apologize for the delay this was somehow missed from my radar. Change looks good to me, will approve and merge this.

**Review by SaranBalaji90 — APPROVED** [review]

**Pull request merged**
